services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code/  # Hot-reload: si cambias código en tu PC, se actualiza en Docker
    depends_on:
      - db
      - redis # Ahora depende de redis también
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --- NUEVO: WORKER (El ejecutor de Bots) ---
  worker:
    build: .
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/code/
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}  # <--- ¡MÁS SEGURO!
    env_file:
      - .env

  # 👇 NUEVO SERVICIO: EL PROGRAMADOR
  beat:
    # El comando es diferente: usa 'beat' en vez de 'worker'
    command: celery -A app.tasks beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db
  # --- NUEVO: REDIS (La Cola) ---
  redis:
    image: redis:7-alpine

  adminer:
    image: adminer
    restart: always
    ports:
      # El formato es "PUERTO_EXTERNO:PUERTO_INTERNO"
      - "8080:8080"

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: "2gb" # Importante: Chrome consume mucha memoria compartida
    ports:
      - "4444:4444" # Puerto estándar de Selenium Grid
    environment:
      - SE_NODE_MAX_SESSIONS=1 # Un navegador a la vez para no explotar tu PC

  frontend:
    build: ./frontend
    ports:
      - "4200:4200" # Puerto estándar de Angular
    volumes:
      - ./frontend:/app # Hot-reload: Si editas en VS Code, se actualiza en Docker
      - /app/node_modules # Truco: Evita que Docker sobrescriba las librerías con tu carpeta local vacía
      - /app/.angular
    depends_on:
      - web
volumes:
  postgres_data: